build:
  test:
    image: python:2.7-alpine
    environment:
      ENV: CI
    commands:
      - echo "this is a python app  "
    when:
      event:
        - push

# runs `docker build` and `docker push` to the specified GCR
publish:
  gcr:
    repo: inspiring-cat-165403/rhizome
    tag: "$$COMMIT"
    token: >
       $$GOOGLE_CREDENTIALS
    storage_driver: overlay
    when:
      branch: master
      event: push
