language: python
python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_9f1ee704bc4a_key -iv $encrypted_9f1ee704bc4a_iv -in rhizome.pem.enc -out ./rhizome.pem -d
before_script:
  - sh -c "psql -c 'CREATE ROLE djangoapp WITH SUPERUSER LOGIN;' -U postgres; fi"
  - npm install -g npm@latest
  - npm install -g babel-eslint@4.1.6
  - cd webapp/ && npm install && npm install -g gulp && cd ..

script:
  - python manage.py test --settings=rhizome.settings.test
  - cd webapp && gulp build && gulp mocha && cd ..

notifications:
  slack: rhisome:$SLACK_ACCESS_KEY

after_success:
  - chmod 400 rhizome.pem
  - mv rhizome.pem ~/.ssh/rhizome.pem
  - ssh -i ~/.ssh/rhizome.pem ubuntu@52.2.128.26
  - fab -H rhizome_test deploy
