version: 0.0

os: linux

files:
  - source: /rhizome
    destination: ~/deploy/rhizome-work
permissions:
  - object: /rhizome
    pattern: "**"
    mode: 777
hooks:
  ApplicationStop:
    - location: bin/auto_deploy/stop_apache.sh
      timeout: 1800
      runas: root
  BeforeInstall:
    - location: bin/auto_deploy/build_dependencies.sh
      timeout: 1800
      runas: root
  AfterInstall:
    - location: bin/auto_deploy/database_init.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: bin/auto_deploy/start_apache.sh
      timeout: 1800
      runas: root
