version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/apps/rhizome/
permissions:
  - object: /var/www/apps/rhizome/
    pattern: "**"
    mode: 777
hooks:
  BeforeInstall:
    - location: bin/auto_deploy/cleanup.sh
      timeout: 1800
      runas: root
  ApplicationStop:
    - location: bin/auto_deploy/stop_apache.sh
      timeout: 1800
      runas: root
  AfterInstall:
    - location: bin/auto_deploy/database_init.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: bin/auto_deploy/start_apache.sh
      timeout: 1800
      runas: root
