rhizome:
  restart: always
  build: .
  links:
    - db:postgres ## should't this be `db:db` ?
  expose:
    - 9090
  ports:
    - 9090:9090
  volumes:
    - .:/rhizome
  working_dir: /rhizome
  entrypoint: /rhizome/bin/start.sh

db:
  restart: always
  image: postgres:9.3
  expose:
    - 5432
  ports:
    - 5432:5432
  hostname: psqlserver
  env_file:
  - .env-example
  environment:
    POSTGRES_DB: rhizome
    POSTGRES_USER: djangoapp
    POSTGRES_PASSWORD: w3b@p01i0
    SECRET_KEY: 1234mxmxmxmxm

# fe:
#   build: webapp
#   volumes:
#     - ./webapp:/code
#   env_file:
#     - .env-example
#   entrypoint: /code/gulp_dev.sh
